import React from "react";
import Link from "next/link";

const pages = [
    {
        name: "Home",
        link: "/",
        description: 'home page',
        metaTitle: 'Create Next App',
        metaDescription: 'Generated by create next app',
    },
    {
        name: "The Undercover",
        link: "/theundercover",
        description: 'the undercover game page',
        metaTitle: 'The undercover',
        metaDescription: 'the undercover on the hsp website',
    },
    {
        name: "Elliptical Orbit Art",
        link: "/ellipticalorbitart",
        description: 'elliptical orbit art page',
        metaTitle: 'create art',
        metaDescription: 'elliptical art on the hsp website',
    },
];

const CustomNavbar: React.FC = () => {
    return (
        <header>
            <div>
                <nav className="mx-auto flex max-w-7xl items-center justify-between p-6 bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none" aria-label="Global">
                    {pages.map((page, index) => 
                    (
                        <Link key={index} href={page.link} className="underline decoration-transparent transition duration-300 ease-in-out hover:decoration-inherit font-mono font-bold">
                            {page.name}
                        </Link>
                    ))}                
                </nav>
            </div>
        </header>
    )
}

export default CustomNavbar;